baseURL = "http://example.org/"
title = "My Personal Website"
copyright = "XXX. All Rights Reserved."
languageCode = "en-us"
sectionPagesMenu = "main"
theme = "bs4"

disqusShortname = ""
googleAnalytics = ""

###
# MAIN MENU
#   Note: custome "main" menu items, e.g. changing weight, name, or link title attribute. `identifier` must match the section name
###
[[menu.main]]
  name = "About"
  title = "About Section"
  weight = 100
  identifier = "about"
  url = "/about/"
[[menu.main]]
  name = "TOC"
  title = "Table Of Content"
  weight = 90
  identifier = "toc"
  url = "/toc/"
[[menu.main]]
  name = "Posts"
  title = "Posts Section"
  weight = 10
  identifier = "posts"
  url = "/posts/"

###
# TAXONOMY
#   Note: singular -> plural
###
[taxonomies]
  tag = "tags"
  series = "series"
  category = "categories"

###
# SITEMAP
###
[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  # Please set enviorment variable HUGO_ENV="production" or change the following configuration when you deploy your site.
  env = "dev"
  
  # The favicon icon's url
  favicon = "favicon.ico"
  
  # The Description for your site
  description = "Life is a playground or nothing."
  
  # Page header: jumbotron, hero, carousel
  page_header = "hero"
  
  # The page body element style classes, spearated by space  
  body_class = ""
  
  # Define main sections list
  main_sections = ["posts", "about"]
  
  # Show how many recent posts of each main section
  recent_posts_number = 10
  
  # load 3rd party javascript libaray
  fixie = true
  mathjax = false
  pangu = false
  typekit = false
  fontawesome = false
  holder = false
  clipboard = true

  # load 3rd party css library
  simplelineicons = false
  devicons = false

  # page featured image's url
  featured_img = ""

  # list how many related pages
  related_posts_number = 6
  
  # page components
  include_toc = true
  include_share = true
  include_comment = true
  include_sidebar = true
  
  # Contact Information
  [params.contact]
  facebook = "http://facebook"
  twitter = "http://twitter"
  instagram = "http://instagram"
  youtube = "http://youtubu"
  linkedin = "http://linkedin"
  github = "http://github.com"
  weibo = "http://weibo"
  email = "nobody@example.com"
  email1 = "nobody@example.com"
  email2 = "anotherbody@example.com"

  # Navbar Component
  [params.navbar]
  # element id
  id = "header-navbar"
  # responsive breakpoint: xs, sm, md, lg, xl
  breakpoint = "md"
  # https://getbootstrap.com/docs/4.1/utilities/colors/
  bg_color = "dark"
  # background color mode: light, dark
  bg_mode = "dark"
  # https://getbootstrap.com/docs/4.1/utilities/borders/#border-color
  bottom_border_color = ""
  # Brand image
  brand_img = ""

  # Hero header Component
  [params.hero]
  # element id
  id = "header-lead"
  color = "white"
  bg_color = "dark"
  
  # Jumbotron header Component
  [params.jumbotron]
  id = "header-lead"
  color = ""
  bg_color = ""

  # Carousel header Component
  [params.carousel]
  id = "header-lead"
  fade = false
  # specify the section'll be showed on carousel
  section = "posts"